version: '3'

volumes:
  mysql_data:
services:
  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/backend'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
